title: "Welcome to Spress"
description: "A site creted by Spress"
logo: "spresso-logo.png"

parsedown_actived: true

# Collections
collections:
  posts:
    output: true

  projects:
    output: true

# Code highlight for <pre> and <code> tags
# Powered by http://highlightjs.org/
code_highlight: true

include: ['/code/wordpress-sites/gettwigusetwigsmile.com/wp-content/themes/twig-theme/templates/partials']

# Page menus
side_menu:
    - { name: Home, url: "/" }
    - { name: Typeography, url: "/type" }
    - { name: Buttons, url: "/buttons" }
    - { name: Widgets, url: "/widgets" }
    - { name: Media Object, url: "/media-object" }
    - { name: Tease, url: "/tease" }
    - { name: Code Highlight, url: "/code" }

